### ISSUE TITLE
Filter parsed as action

### ISSUE THREAD

**Issue by djmadeira** [rmccue/WP-Parser#128]
The doc entry for the filter `enter_title_here` looks like this:
![screen shot 2014-09-02 at 1 34 18 pm](https://cloud.githubusercontent.com/assets/5123044/4122720/6828b0fc-32c7-11e4-8272-e7cb1eafc29e.png)

The code looks like this:
![screen shot 2014-09-02 at 1 28 15 pm](https://cloud.githubusercontent.com/assets/5123044/4122676/f9f4f258-32c6-11e4-9c0e-ff3679c24247.png)

The filter is categorized as an action, and the wrong documentation is attached to it.

**Comment by JDGrimes** [comment]
Related WordPress trac ticket: [#30558](https://core.trac.wordpress.org/ticket/30558)

That fixed the issue for the [`enter_title_here`](https://developer.wordpress.org/reference/hooks/enter_title_here/) hook.

This can be closed, I think.
