### ISSUE TITLE
Incorrect Used By and Uses info for lowercase_octets()

### ISSUE THREAD

**Issue by atimmer** [rmccue/WP-Parser#153]
Copied from: https://meta.trac.wordpress.org/ticket/942

---

See https://developer.wordpress.org/reference/functions/lowercase_octets/

The function is declared inside of [redirect_canonical()](https://core.trac.wordpress.org/browser/tags/4.1/src/wp-includes/canonical.php#L451), and that is likely the cause.

**Comment by JDGrimes** [comment]
I was able to do some work on this yesterday. I still need to do some testing before I open a PR.
