### ISSUE TITLE
Tokenizer

### ISSUE THREAD

**Issue by parkerj** [rmccue/WP-Parser#160]
I installed via the instructions, but when I run the parser command, I get the following error message:
```
PHP Fatal error:  Call to undefined function token_name() in /Applications/AMPPS/www/wp/wp-content/plugins/wp-parser/vendor/nikic/php-parser/lib/PHPParser/Lexer.php on line 190
```
Is there something missing in my configuration?

**Comment by Rarst** [comment]
That function is from [Tokenizer](http://php.net/manual/en/book.tokenizer.php) extension, it _might_ be disabled as far as I understand docs.

You can run `composer show --platform` and check for `ext-tokenizer` in the list.

**Comment by Rarst** [comment]
By the way I checked and PHP Parser should require this via its `composer.json`, Composer should have warned you if the extension was missing. Unless you installed on one system and then moved to another.

**Comment by parkerj** [comment]
The only difference is that I relocated composer.phar after the install in order to just use the command composer (/usr/local/bin/composer). Could that have anything to do with it?

**Comment by Rarst** [comment]
Sometimes there are quirks with different PHP versions in the system and stuff. You need to figure out:

1. Which PHP runtime you are using when getting the error.
2. Does it have tokenizer extension enabled.

**Comment by parkerj** [comment]
I am using AMPPS. I was getting the MySQL error, I had to set it up to see my configuration:

PHP 5.3.29 (cli) (built: Nov  5 2014 14:13:13)

As far as I can see, tokenizer is in the list and enabled.

**Comment by Rarst** [comment]
Not sure if related, but version is below requirements. WP Parser requires PHP >=5.4 in its `composer.json`. Again, Composer should have complained about this on install...

PHP 5.3 is obsolete, I would recommend updating to a stable version in any case. :)

**Comment by parkerj** [comment]
Ah, didn't realize that. Reverted back to PHP 5.4.35 (cli) (built: Nov 17 2014 17:19:43) and it is working. Thank you.
